In [1]:
import torch

In [2]:
from pytorch101 import create_sample_tensor, create_tensor_of_pi

In [3]:
create_sample_tensor()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
create_tensor_of_pi(4,3)
print(create_tensor_of_pi(4,3))

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])


In [5]:
from pytorch101 import count_tensor_elements
count_tensor_elements(create_tensor_of_pi(4,3))

12

In [6]:
from pytorch101 import create_tensor_of_pi
print(create_tensor_of_pi(4,3))

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])


In [7]:
from pytorch101 import calculate_tensor_sum
x = create_sample_tensor()
print(x)
print(calculate_tensor_sum(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(0.)


In [8]:
from pytorch101 import divisible_by_five
print(divisible_by_five(2, 39))

tensor([ 5., 10., 15., 20., 25., 30., 35.])


In [9]:
import importlib
import pytorch101
importlib.reload(pytorch101)

from pytorch101 import create_sample_tensor, calculate_tensor_sum

x = create_sample_tensor()
print(x)
print(calculate_tensor_sum(x))
print(create_tensor_of_pi(4,3))
print(count_tensor_elements(create_tensor_of_pi(4,3)))
print(divisible_by_five(2, 39))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(0.)
tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])
12
tensor([ 5., 10., 15., 20., 25., 30., 35.])


In [10]:
import importlib
import pytorch101
importlib.reload(pytorch101)

x = pytorch101.create_sample_tensor()
print(x)
print(pytorch101.calculate_tensor_sum(x))
print(pytorch101.create_tensor_of_pi(4, 3))
print(pytorch101.count_tensor_elements(pytorch101.create_tensor_of_pi(4,3)))
print(pytorch101.divisible_by_five(2, 39))


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(0.)
tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])
12
tensor([ 5., 10., 15., 20., 25., 30., 35.])


In [11]:
print(pytorch101.count_nonzero_elements(pytorch101.create_tensor_of_pi(4,3)))

12


In [14]:
x = torch.tensor([i for i in range(36)])
print(pytorch101.reshape_practice_v2(x))
# print(y)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]])
tensor([[ 0,  1,  2, 12, 13, 14, 24, 25, 26],
        [ 3,  4,  5, 15, 16, 17, 27, 28, 29],
        [ 6,  7,  8, 18, 19, 20, 30, 31, 32],
        [ 9, 10, 11, 21, 22, 23, 33, 34, 35]])


NameError: name 'y' is not defined

In [18]:
importlib.reload(pytorch101)
pytorch101.reshape_practice_v2(x)

tensor([[ 0,  1,  2, 12, 13, 14, 24, 25, 26],
        [ 3,  4,  5, 15, 16, 17, 27, 28, 29],
        [ 6,  7,  8, 18, 19, 20, 30, 31, 32],
        [ 9, 10, 11, 21, 22, 23, 33, 34, 35]])

In [26]:
importlib.reload(pytorch101)
print(pytorch101.zero_min_in_each_row(torch.tensor([[1, 2, 3], [4, 5, 6]])))

tensor([[0, 2, 3],
        [0, 5, 6]])


In [32]:
importlib.reload(pytorch101)
pytorch101.batch_matrix_multiply(torch.tensor([[[1, 2], [3, 4]],[[5,6],[7,8]]]), torch.tensor([[[5, 6], [7, 8]],[[9, 10], [11, 12]]]))

tensor([[[ 19,  22],
         [ 43,  50]],

        [[111, 122],
         [151, 166]]])

In [35]:
importlib.reload(pytorch101)
pytorch101.gpu_matrix_multiplication(
    torch.tensor([[1, 2], [3, 4]]).float(),
    torch.tensor([[1, 2], [3, 4]]).float()
)

tensor([[ 7., 10.],
        [15., 22.]])